config/routes.rb
Rails.application.routes.draw do
  root 'gossip#index'

  resources :gossip do
    resources :comments, shallow: true do
      resources :comments, defaults: { commentable: 'comment' }
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'comment' }
    end
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'gossip' }
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :tags

  resources :users
  resources :cities, only: :show

  get '/contacts', to: 'static#contacts'
  get '/team', to: 'static#team'
  get '/welcome/:name', to: 'static#welcome'

  post '/update_location', to: 'users#update_location'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  after_create :set_location
  attr_accessor :tag_ids

  validates :title, presence: true, length: { in: 2..14 }
  validates :content, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :user

  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  has_many :comments, as: :commentable

  has_many :likes, as: :likeable

  def set_location
    self.longitude = user.longitude
    self.latitude = user.latitude
    save!
  end
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/message_recipient.rb
class MessageRecipient < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: 'User'
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :message_recipients
  has_many :recipients, through: :message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, presence: true
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "must be a valid email address"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_nil: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_nil: true

  belongs_to :city
  has_many :gossips

  has_many :sent_messages, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :message_recipients, foreign_key: :recipient_id
  has_many :received_messages, through: :message_recipients, source: :private_message

  has_many :comments

  has_many :likes
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  include GossipHelper
  before_action :authenticate_user, except: [:index]

  def index
    @gossips = Gossip.all
    if current_user
      @nearby_gossip = nearby_gossip || []
    else
      @nearby_gossip = []
    end
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
  end

  def new
    @tags = Tag.all
  end

  def create
    @tags = Tag.all
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)

    if @gossip.save
      create_tags(@gossip, params[:gossip][:tag_ids])

      flash[:notice] = 'Gossip creation successful'
      redirect_to gossip_path(@gossip.id)
    else

      flash.now[:alert] = error_string(@gossip)
      render :new
    end
  end

  def edit
    @tags = Tag.all
    @gossip = Gossip.find(params[:id])
  end

  def update
    @tags = Tag.all
    @gossip = Gossip.find(params[:id])

    if check_if_current_user(@gossip.user) && @gossip.update(gossip_params)
      create_tags(@gossip, params[:gossip][:tag_ids])
      flash[:notice] = 'Gossip updated successful'
      redirect_to gossip_path(@gossip.id)
    else
      flash.now[:alert] = 'Failed to update gossip'
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if check_if_current_user(@gossip.user) && @gossip.destroy
      flash[:notice] = 'Gossip deleted successfully'
      redirect_to gossip_index_path
    else
      flash.now[:alert] = 'Failed to delete gossip'
      render :show
    end
  end

  private

  def record_not_found
    flash[:alert] = '404 not found'
    redirect_to :back
  end

  def gossip_params
    params.require(:gossip).permit(:title, :content, :user_id)
  end

  def create_tags(gossip, tag_ids)
    @gossip.tags.clear
    params[:gossip][:tag_ids].each do |tag_id|
      GossipTag.create(gossip: @gossip, tag_id: tag_id)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user
  before_action :set_likeable, only: [:create]

  def create
    @like = @likeable.likes.new(user: current_user)
    flash[:alert] = error_string(@like) unless @like.save
    redirect_back_or_to gossip_path(root_gossip_id(@like))
  end

  def destroy
    @like = Like.find(params[:id])

    flash[:alert] = error_string(@like) unless @like.destroy

    redirect_back_or_to gossip_path(root_gossip_id(@like))
  end

  private

  def root_gossip_id(like)
    like.likeable.instance_of?(Gossip) ? like.likeable.id : like.likeable.commentable.id
  end

  def set_likeable
    @likeable = params[:likeable].classify.constantize.find(params[:like][:likeable_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @gossips = @tag.gossips
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_card_class
    ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/geolocation_helper.rb
# frozen_string_literal: true

module GeolocationHelper
  def within_50_meters?(point1, point2)
    if point1.latitude && point1.longitude && point2.latitude && point2.longitude
      lat1 = point1.latitude
      lon1 = point1.longitude
      lat2 = point2.latitude
      lon2 = point2.longitude

      radius_of_earth = 6371e3
      latitude1_rad = lat1 * Math::PI / 180
      latitude2_rad = lat2 * Math::PI / 180
      change_in_latitude_rad = (lat2 - lat1) * Math::PI / 180
      change_in_longitude_rad = (lon2 - lon1) * Math::PI / 180

      a = Math.sin(change_in_latitude_rad / 2)**2 +
          Math.cos(latitude1_rad) * Math.cos(latitude2_rad) *
          Math.sin(change_in_longitude_rad / 2)**2
      c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))

      distance = radius_of_earth * c

      distance <= 50
    else
      false
    end
  end
end

app/helpers/gossip_helper.rb
module GossipHelper
  include GeolocationHelper
  def nearby_gossip
    Gossip.all.filter { |gossip| within_50_meters?(gossip, current_user) }
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def check_if_current_user(user)
    user == current_user
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossip/_comment_likes.html.erb
<div class="container d-flex flex-row m-2 justify-content-end">
  <% if comment.likes.map(&:user).include?(current_user) %>
    <% like = comment.likes.find_by(user: current_user) %>
    <%= form_with(model: like, url: like_path(like), method: :delete, local: true) do |form| %>
      <button name="commit" type="submit" class="btn btn-success">
        Remove Like <span class="badge text-bg-secondary"><%= comment.likes.count %></span>
      </button>
    <% end %>

  <% else %>
    <%= form_with(model: Like.new , url: comment_likes_path(comment), local: true) do |form| %>
      <%= form.hidden_field :likeable_id, value: comment.id %>
      <button name="commit" type="submit" class="btn btn-success">
        Like <span class="badge text-bg-secondary"><%= comment.likes.count %></span>
      </button>
    <% end %>
  <% end %>
</div>

app/views/gossip/_comment_on_comments_index.html.erb
<div class="container">
  
  <% comment.comments.each do |comment| %>
    <h5>By: <%= comment.user.first_name %></h5>
    <p><%= comment.content %></p>
    <% if check_if_current_user(comment.user) %>
      
      <div class="d-flex justify-content-center">
        <%= button_to "Edit comment",
          edit_comment_path(
            id: comment.id
          ),
          method: :get,
          class: "btn btn-warning mx-2"
        %>

        <%= button_to "Delete comment",
          comment_path(
            id: comment.id
          ),
          method: :delete,
          class: "btn btn-danger mx-2"
        %>
      </div>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/gossip/_comment_on_comments_new.html.erb
<div class="container">
  <div class="container m-2">
    <div class="d-flex flex-column">
      <%= form_with(model: Comment.new, url: comment_comments_path(comment), local: true) do |form| %>
        <%= form.hidden_field :comment_id, value: comment.id %>
        <%= form.label "Write your comment:", class: "form-label" %>
        <br>
        <%= form.text_area :content, class: "form-control" %>
        <br>
        <%= form.submit "Post", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/gossip/_index.html.erb
<% color_options = ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'] %>
<div class="d-flex flex-wrap justify-content-evenly">
  <% gossips.each_with_index do |gossip, index| %>
    <div class="p-3 m-2 rounded-pill card <%= color_options[index % color_options.length] %>" style="width: 18rem;" >
      <div class="card-body">
        <div class="d-flex justify-content-center">
          <div>
            <h5 class="card-title text-dark"><%= gossip.title %></h5>
            <p class="card-text text-dark">By: <%= gossip.user.first_name %></p>
          </div>
        </div>

        <% if current_user %>

          <div class="d-flex flex-column align-items-center">
            <%= render partial: "likes/likes", locals: { gossip: gossip} %>
            <%= link_to 'Go to gossip', gossip_path(id: gossip.id), class:'btn btn-dark' %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/gossip/_tags_index.html.erb
<div class="container d-flex flex-wrap">
  
  <% gossip.tags.each do |tag| %>
    <span class="d-inline-block rounded-pill px-2 py-1 text-bg-light">
    <%= link_to tag.title, tag_path(tag.id)  %></span>
     
  <% end %>
</div>

app/views/gossip/edit.html.erb
<div class="container card p-3 <%= ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample %> text-dark">
  <h1>Edit Gossip:</h1>
  <%= form_tag url_for(action: 'update'), method: :patch do %>
    <div class="mb-3">
      
      <%= label_tag :title, "Gossip Title", class: "form-label" %>
      <%= text_field_tag 'gossip[title]', @gossip.title, class: "form-control" %>
    </div>
    <div class="mb-3">
      
      <%= label_tag :content, "Gossip Content", class: "form-label mt-2" %>
      <%= text_area_tag 'gossip[content]', @gossip.content, class: "form-control" %>
    </div>
    <div class="mb-3">
      
      <%= label_tag :tags, "Tags", class:"form-label" %>
      <div class="d-flex flex-wrap justify-content-evenly">
        
        <%= collection_check_boxes(:gossip, :tag_ids, @tags, :id, :title) do |box| %>
          <div class="form-check m-2">
            <%=  box.check_box(class: "form-check-input", checked: @gossip.tags.include?(box.object))  %>
            <%= box.label(class: "form-check-label") %>
          </div>
        <% end %>
      </div>
    </div>
    <%= submit_tag  "Update post", class: "btn btn-dark" %>
  <% end %>
  
</div>

app/views/gossip/index.html.erb
<div class="jumbotron jumbotron-fluid d-flex align-items-center" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= asset_path('jumbotron-image.jpg') %>); background-size: cover; height: 40vh; background-position: 50% 50%; ">
  <div class="container text-center">
    <% if current_user %>
      <h1 class="display-4">Welcome To The Gossip Project, <%= current_user.first_name %></h1>
    <% else %>
      <h1 class="display-4">Welcome To The Gossip Project</h1>
      
    <% end %>
  </div>
</div>

<div class="container">
  
  <div class="d-flex flex-column justify-content-evenly">

    <div class="container d-flex flex-row justify-content-center m-2"> <% if current_user %>
        <%= button_to 'Create Gossip', new_gossip_path, method: :get, class:'btn btn-dark' %>
      <% end %>
    </div>
    <div class="container d-flex flex-row justify-content-center m-2">
      <%= button_to 'Find by tag', tags_path, method: :get, class:'btn btn-dark' %>
    </div>
    <h3>Nearby Gossip</h3>
    <p class="padded-text text-center fw-bolder">Scan the area for gossip</p>
    <div class="d-flex justify-content-center">
        <button data-controller="geolocation" data-action="click->geolocation#startGeolocation" class="btn btn-success">Scan</button>
    </div>
    <%= render partial: "gossip/index", locals: { gossips: @nearby_gossip } %>

    <h3>All Gossip</h3>
    <%= render partial: "gossip/index", locals: { gossips: @gossips } %>
  </div>
</div>

app/views/gossip/new.html.erb
<div class="container card p-3 <%= ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample %> text-dark">
  <h1>What's the tea?</h1>
  <%= form_tag url_for(action: 'create'), method: :post do %>
    <div class="mb-3">
      
      <%= label_tag :title, "Gossip Title", class: "form-label" %>
      <%= text_field_tag :title, nil, class: "form-control" %>
    </div>
    <div class="mb-3">
      
      <%= label_tag :content, "Gossip Content", class: "form-label mt-2" %>
      <%= text_area_tag :content, nil, class: "form-control" %>
    </div>
    <div class="mb-3">
      
      <%= label_tag :tags, "Tags", class:"form-label" %>
      <div class="d-flex flex-wrap justify-content-evenly">
        
        <%= collection_check_boxes(:gossip, :tag_ids, @tags, :id, :title) do |box| %>
          <div class="form-check m-2">
            <%=  box.check_box(class: "form-check-input")  %>
            <%= box.label(class: "form-check-label") %>
          </div>
        <% end %>
      </div>
    </div>
    <%#= select_tag "tag_ids[]", options_from_collection_for_select(@tags, "id", "title"), multiple: true, class: "form-control" %>
    <%= submit_tag  "Create post", class: "btn btn-dark" %>
  <% end %>
  
</div>

app/views/gossip/show.html.erb
<div class="container mt-3">

  <div id= "show-gossip-outer" class="d-flex flex-column justify-content-center align-items-center">
    <div class="p-4 card <%= ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample %> rounded-pill" >
      <div class="card-body">
        <div id="show-gossip-path" class="d-flex justify-content-center">
          <div>
            <h3 class="card-title text-center text-dark"> <%= @gossip.title %></h3>
            <h5 class="card-title text-dark">By: <%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}" , user_path(id: @gossip.user.id), class: "link-dark" %></h5>
            <h5 class="card-title text-dark">City: <%= link_to @gossip.user.city.name, city_path(@gossip.user.city_id), class: "link-dark" %></h5>

            <p class="card-text text-dark"><%= @gossip.content %></p>
            <%= render partial: "tags/tags_index", locals: { tags: @gossip.tags } %>
            <% if check_if_current_user(@gossip.user) %>
              <div class="container d-flex flex-row m-2 justify-content-center">
                <%= button_to 'Edit', edit_gossip_path(@gossip.id), method: :get, class:'btn btn-warning me-1' %>
                <%= button_to 'Delete', gossip_path(@gossip.id), method: :delete, class:'btn btn-danger ms-1' %>
              </div>
            <% end %>
            <%= render partial: "likes/likes", locals: { gossip: @gossip } %>
          </div>
        </div>
      </div>
    </div>
    <div id="comments-util" class="container m-5">
      <%= render partial: "comments/comments_new", locals: { comment: @comment, gossip: @gossip } %>
      <div id="comment-count" class="p-2 card d-flex <%= ['card-bg-1', 'card-bg-2', 'card-bg-3', 'card-bg-4', 'card-bg-5'].sample %> flex-wrap m-1">
        <div class="card-body w-30">
          <div class="d-flex flex-column">
            <h5>This gossip has <%= @gossip.comments.count %> comments.</h5>
          </div>
        </div>
      </div>
      <%= render partial: "comments/comments_index", locals: { gossip: @gossip } %>
    </div>
  </div>
</div>